#!/usr/bin/env bash
# Script that adds a redirect url

sed -i "/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
service nginx restart
