#!/usr/bin/env bash
# Script that adds a redirect url
apt update -y
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
service nginx restart
sed -i "/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
service nginx restart
