#!/usr/bin/env bash
# Infinite loop with traps
echo "$$" > /var/run/holbertonscript.pid
trap "{ echo I hate the kill command; rm /var/run/holbertonscript.pid; exit 0; }" SIGTERM
trap "{ echo Y U no love me?!; rm /var/run/holbertonscript.pid; exit 0; }" SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
