#!/usr/bin/env bash
# Controle my_process
start() {
	./manage_my_process &
	pid=$(pgrep -fn manage_my_process)
	echo "$pid" > /var/run/my_process.pid
}

stop() {
	process=$(</var/run/my_process.pid)
	kill -9 "$process"
	rm /var/run/my_process.pid
}

case "$1" in
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
