#!/usr/bin/env bash
#Print /etc/passwd content

input="/etc/passwd"

while IFS= read -r line
do
	user=$(echo "$line" | cut -d ":" -f 1)
	gid=$(echo "$line" | cut -d ":" -f 4)
	home=$(echo "$line" | cut -d ":" -f 6)
	shell=$(echo "$line" | cut -d ":" -f 7)
	uid=$(echo "$line" | cut -d ":" -f 3)
	pass=$(echo "$line" | cut -d ":" -f 2)
	uidinfo=$(echo "$line" | cut -d ":" -f 5)
	
	res="The user ${user} is part of the ${gid} gang, lives in ${home} and rides ${shell}. ${uid}'s place is protected by the passcode ${pass}, more info about the user here: ${uidinfo}"
	echo "$res"
done < "$input"
