#!/usr/bin/env bash
# Script that repair web debbunging server
#sudo service apache2 stop
sudo pkill -o apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
